### ISSUE TITLE
Explicitly specify all rule options

### ISSUE THREAD

**Issue by rostislav-simonik** [mightyiam/eslint-config-love#1003]
To prevent unintentional changes on plugin bumps.

**Comment by mightyiam** [comment]
Upstream doesn't yet have this policy. [Proof](https://github.com/standard/eslint-config-standard/blob/54a86c52721d4331d6c8ef4fd1ce055cc919f2ba/src/index.ts#L73C18-L73C23). Rule has [options](https://eslint.org/docs/latest/rules/eol-last#options). So we're not adopting this policy yet.

https://github.com/standard/eslint-config-standard/issues/375
