### ISSUE TITLE
[feature request]: cut down on peer dependencies

### ISSUE THREAD

**Issue by rhettjay** [mightyiam/eslint-config-love#1210]
**What version of this package are you using?**
^37.0.0
**What problem do you want to solve?**
Peer dependencies
**What do you think is the correct solution to this problem?**
According to eslint the [issue](https://github.com/eslint/eslint/issues/3458) necessitating the use of peer dependencies was resolved in [v8.2.1](https://eslint.org/blog/2022/08/new-config-system-part-1/).  What plans (if any) are there to update to 8.2.1 and cut down on the peer dependencies?
**Are you willing to submit a pull request to implement this change?**
More than happy to. I'm not familiar with the library so I would need some guidance.

**Comment by mightyiam** [comment]
Totally wanna do this. Work on this would begin upstream eslint-config-standard.

**Comment by jay-bulk** [comment]
What needs to be done there? How can I help? The version there is [8.13](https://github.com/standard/eslint-config-standard/blob/7d01bbc373bf3bb7374b698323032077ad05f6b1/package.json#L19) which is above the 8.2.1 fix so I'm a little confused on how to start here.

**Comment by mightyiam** [comment]
Best way to help is to apply for participation in our mob:
https://mobusoperandi.com/mobs/standard.html
