### ISSUE TITLE
Safety of calling unbound methods

### ISSUE THREAD

**Issue by mightyiam** [mightyiam/eslint-config-love#1327]
[Apparently, TypeScript, even in `strict` mode, couldn't care less about the type of `this` while calling an unbound method](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oFsCmAXAFvACYAUAlCuhtMPAHYTwjYB0I8A5iQQJYQs4CxMlQC+qcaloNc0AGaJoAXmh1sAdziJyU+hFnIseQkWijl8xKkEny0APT3oAJwCudXDxzRsz5-GdoACJeGD5odyJsOR41IiCgA).

The only way to enforce such safety is to enforce declaration of `this` in functions where `this` is used.

And yet, [I don't see such a rule in typescript-eslint](https://discord.com/channels/1026804805894672454/1170252804351328256).

**Comment by mightyiam** [comment]
Another option is the `[unbound-method](https://typescript-eslint.io/rules/unbound-method)` lint rule. But it doesn't allow having unbound methods, which could be valid, albeit somewhat strange.

**Comment by rostislav-simonik** [comment]
We have follow-up discussion on [discord](https://discord.com/channels/1026804805894672454/1175327019890909235) for `no-unsafe-*` check 

And that would require also modification in `unbound-method` rule to exclude `this: <with type>`

**Comment by mightyiam** [comment]
I think we're happy with `no-unsafe-*` rules.
