### ISSUE TITLE
Unexpected top-level property "languageOptions"

### ISSUE THREAD

**Issue by MonkiG** [mightyiam/eslint-config-love#1559]
I'm using:

`
eslint-config-love": "48.0.0"
`

 When i run 

`
npx eslint . 
`

the console shows me this error:
```sh
Oops! Something went wrong! :(
ESLint: 8.57.0
Error: ESLint configuration in .eslintrc.json » eslint-config-love is invalid:
        - Unexpected top-level property "languageOptions".
```
This is my .eslitrc.json file:
```json
{
  "extends": "love",
  "overrides": [{
      "files": ["*.js", "*.ts"]
  }]
}
```
This error doesn't occur with:

`
eslint-config-love": "47.0.0"
`

using the same .eslintrc.json configuration

**Comment by mightyiam** [comment]
Make sure you're using ESLint flat configuration. Or the compatibility utility, if you can't do that, yet.

**Comment by MonkiG** [comment]
Thanks for the help, in order to solve this I change the config file name to: eslint.config.cjs and put this config:
```JavaScript
const love = require('eslint-config-love')
module.exports = [
    {
        ...love,
        files: ['src/*.{js,ts,tsx,jsx}'],
        rules: {
            ...love.rules
        }
    }
]
```
With this I was able to run 
```sh
npx eslint .
``` 

Now, if someone wants to fix the files on save you need to config the vscode eslint plugin depending on its version,
if the vscode extension version is the pre-release 3.0.5 you need to add this to you settings.json:
```json
{
  //your editor config,
  "eslint.useFlatConfig": true,
}
```
and if the extension version is behind the pre-release you need you use:
```json
{
  //your editor config,
  "eslint.experimental.useFlatConfig":true
}
```
