### ISSUE TITLE
What is this project about?

### ISSUE THREAD

**Issue by sacru2red** [mightyiam/eslint-config-love#1578]
I am using "eslint-config-standard-with-typescript" why I think Its standard project
npm say "eslint-config-standard-with-typescript" change to "eslint-config-love", so I updated package.json.

and I read https://github.com/standard/standard/issues/1957

but, 
I don't understand it properly. Where is this project going? README.md seems to be lacking a lot of explanation about this project.

thank you.

@mightyiam

**Comment by mightyiam** [comment]
Thank you, @sacru2red . I added a few details to the readme. Does it suffice now?

**Comment by sacru2red** [comment]
@mightyiam 
Since I am not a native English speaker, I used a tool to write the article below.
===

You added the “Guidelines” part, etc. great!

Personally, I think it would be a good to add a "History" part at the bottom of README.md so that users of eslint-config-standard-with-typescript would be less confused.

please check my understanding is correct.

Because eslint-config-standard had insufficient support for ts, eslint-config-standard-with-typescript was created,

The versioning rules of eslint-config-standard seem to be rigid and inconvenient because they are related to the standard project. (In fact, the last update was a year ago, and it seems that eslint's latest configuration files, etc. are not supported.)

On the other hand, eslint-config-standard-with-typescript has been constantly updated and versioned, and has gradually moved away from the standard linter rules, and the project seems to have been separated as written in the issue I mentioned.

Is my understanding correct?

Q. Who should use eslint-config-love? In fact, even after reading the Guidelines, I don't think there are any significant motivating factors to use.

**Comment by mightyiam** [comment]
Thank you for your feedback. I would actually prefer to keep that piece of history out of the readme. Is there any other way to satisfy your concern?

**Comment by sacru2red** [comment]
@mightyiam
No, Thank you mightyiam. have a good day

**Comment by mightyiam** [comment]
So I just did #1641. Does it help?

Yes, it sounds like this config might be what you're looking for. I'd love to hear how you feel about it if you give it a try. And we're totally open to contribution. The easiest contribution is adding rules. See [CONTRIBUTING.md](https://github.com/mightyiam/eslint-config-love/blob/main/CONTRIBUTING.md).

**Comment by psychobolt** [comment]
For awhile now my past projects relied on `eslint-config-standard-with-typescript` to leverage `standard` config. I recently heard of https://github.com/neostandard/neostandard , which is suppose to include Typescript support. Should the [deprecated message](https://www.npmjs.com/package/eslint-config-standard-with-typescript) , direct users to this one (which is unrelated to leveraging `standard`? @mightyiam

**Comment by mightyiam** [comment]
@psychobolt I have control over this project. I'm not involved in neostandard. Neither have I assessed neostandard.
