### ISSUE TITLE
Relax @typescript-eslint/no-magic-numbers

### ISSUE THREAD

**Issue by darkbasic** [mightyiam/eslint-config-love#1786]
Simple tasks like initializing a loop variable to zero with @typescript-eslint/no-magic-numbers current expects that you should create a separate const for zero.
This doesn't happen with @typescript-eslint/no-magic-numbers by default: https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=MYewdgzgLgBAsgQQBowLwwIwAYsG4BQ%2BAZiAE4wAUANgKawCWaMeMjAPPMrqwNQ8CUMAN74YMKAAtSIAO4wwNOQFFS00hX4EAvkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFsBDAc0plaTWNwBGiaKgyQA7r2hNI4MAF8QaoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

I don't think the current eslint-config-love defaults for that rule are acceptable and apparently I'm not the only one that thinks so:

![image](https://github.com/user-attachments/assets/408b9813-23c7-4d14-a559-1836921fe838)

**Comment by mightyiam** [comment]
Sorry and thank you. Will take a look.

**Comment by darkbasic** [comment]
@mightyiam unfortunately it's still not fixed even in latest version:
![image](https://github.com/user-attachments/assets/58dc4504-2f5f-48e0-8cd2-380e00b4bb4e)

**Comment by mightyiam** [comment]
@darkbasic may I please see one of those?

**Comment by darkbasic** [comment]
@mightyiam just some of them:
![image](https://github.com/user-attachments/assets/bba8c331-475a-49dc-9b82-4abc95f5f7fb)
![image](https://github.com/user-attachments/assets/b5111eff-0d9f-429d-93aa-4777262d5797)
![image](https://github.com/user-attachments/assets/68e6e930-8c56-4807-a398-37449b5eb8d3)
![image](https://github.com/user-attachments/assets/a5d52285-5b3f-48fa-94bb-ed23eed7e585)

**Comment by mcereijo** [comment]
I'm facing the same problem with version `89.0.0` and it makes the code much verbose:

```
expect(fetchMock).toHaveBeenCalledTimes(1)
````
Should be changed to:
```
const timesCalled = 1
expect(fetchMock).toHaveBeenCalledTimes(timesCalled)
```

**Comment by darkbasic** [comment]
Yeah this is insane. I get what the rule is meant to achieve, but currently it's doing more harm than good in my opinion and I ended up disabling it in all my projects.

**Comment by darkbasic** [comment]
We should add `-1` as well, since it's the "index not found" value and can be used in `length - 1` as well.

**Comment by mightyiam** [comment]
This configuration is indented to be quite strict.
Please see a readme section we've just added:
https://github.com/mightyiam/eslint-config-love/blob/01af4999a739cb4ec8c51e67c63f0bf3431f5246/README.md#disabling-rules

> @mightyiam just some of them: ![image](https://private-user-images.githubusercontent.com/1047358/377139857-bba8c331-475a-49dc-9b82-4abc95f5f7fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjM3NTEsIm5iZiI6MTcyOTMyMzQ1MSwicGF0aCI6Ii8xMDQ3MzU4LzM3NzEzOTg1Ny1iYmE4YzMzMS00NzVhLTQ5ZGMtOWI4Mi00YWJjOTVmNWY3ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTlUMDczNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2QzNzgxYjc3OWU0M2YwODE1ZWNmMWI0N2Y4OGQ3MWY2MTIxYjRlMjIzZjUyZjZlMGUyMTdlODkyMmNmODQ2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8egqQ-xzciq-K5puTx9weCUjaWMCRUmkrQYUl6X-9hM)

This looks like it may be a legitimate match for this rule. Perhaps something like
```ts
const HEADER_ROW_INDEX = 0
const row = rows[HEADER_ROW_INDEX]
```

Granted, there's a different issue with this, #1830. I will discuss there.

![image](https://private-user-images.githubusercontent.com/1047358/377139992-b5111eff-0d9f-429d-93aa-4777262d5797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjM3NTEsIm5iZiI6MTcyOTMyMzQ1MSwicGF0aCI6Ii8xMDQ3MzU4LzM3NzEzOTk5Mi1iNTExMWVmZi0wZDlmLTQyOWQtOTNhYS00Nzc3MjYyZDU3OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTlUMDczNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2E4Y2JhNTIwZDllNzY5YzY2NzJjZjcyMWJhOGE1NzkxOTU5OWE5NzQzMzk5NmViY2ZiYTNiOWNlYTNkMzVmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lmn0bkfHqg3eS-sf8a0eW8aX-lIPvbOn1IFoi0L2SYY)

Seems like another possible match for this rule. What does 1 pixel stand for? Why one pixel? Perhaps:

```ts
const BORDER_PIXEL_WIDTH = 1
header.width = newValue - BORDER_PIXEL_WIDTH
```

![image](https://private-user-images.githubusercontent.com/1047358/377140439-68e6e930-8c56-4807-a398-37449b5eb8d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjM3NTEsIm5iZiI6MTcyOTMyMzQ1MSwicGF0aCI6Ii8xMDQ3MzU4LzM3NzE0MDQzOS02OGU2ZTkzMC04YzU2LTQ4MDctYTM5OC0zNzQ0OWI1ZWI4ZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTlUMDczNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ3NDRkOWM5OWRkYjRkN2JmZWQxMDFjMGJhZDIwNTY3YmQ3M2JhMDRhNGIxNjFhZjBiZTJlODRjMzlkY2Q1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.E0o9cKcHL5n8qeAU9eSHB4v-TfJ1zm9ze_O2HG9jBJw)

Perhaps a utility `isEmpty` function?

![image](https://private-user-images.githubusercontent.com/1047358/377141033-a5d52285-5b3f-48fa-94bb-ed23eed7e585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjM3NTEsIm5iZiI6MTcyOTMyMzQ1MSwicGF0aCI6Ii8xMDQ3MzU4LzM3NzE0MTAzMy1hNWQ1MjI4NS01YjNmLTQ4ZmEtOTRiYi1lZDIzZWVkN2U1ODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTlUMDczNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmI1NDgyNjNmZTNmNzUxYjgwMzZlY2IyOWZmNDNlYTBhNDkwOTZjOTIwNTdiM2UwZDk3MTQyMDNkMzM0ZWQyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bSqxsH9XSEMFTXdLI8n40ho9SbcQFm70fbo9sQ7m4iU)

This also looks to me like it could use encapsulation as a utility function, in which an `eslint-disable` comment would be appropriate.

 
> ```
> expect(fetchMock).toHaveBeenCalledTimes(1)
> ```

I would disable the rule in the test files in which counts are used. Or maybe all of the test files.

> For what it's worth, it's probably better to set `ignore: [0, 1, 2, 100]` to account for the [accepted uses of magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)#Accepted_limited_use_of_magic_numbers). See [here](https://github.com/menees/Analyzers/blob/master/src/Menees.Analyzers/Settings.cs#L73) for C# variant.

I'm concerned that ignoring specific numbers would reduce the efficacy of the rule.
