### ISSUE TITLE
eslint-comments/require-description is not suitable for generated code

### ISSUE THREAD

**Issue by darkbasic** [mightyiam/eslint-config-love#1880]
Almost every automatically generated code/typings starts with `eslint-disable`:
```ts
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
```

That makes it unsuitable for `eslint-comments/require-description`.

**Comment by mightyiam** [comment]
ESLint is not suitable for generated code.
