### ISSUE TITLE
Cannot find package 'lodash' imported from eslint-config-love\lib\rules.js

### ISSUE THREAD

**Issue by falco467** [mightyiam/eslint-config-love#1892]
Using eslint-config-love@98.0.1, when running eslint.

lodash is only imported as a devDependency, but used by rules.js on execution of eslint.

Seems to be introduced by:
https://github.com/mightyiam/eslint-config-love/commit/41938b31207a5dfd354ba933b19cf9534f4090db

**Comment by mightyiam** [comment]
I mean, in a test.
